"use client"

import { useRef } from "react"
import Link from "next/link"
import Image from "next/image"
import { motion, useInView } from "framer-motion"
import { ArrowLeft, ArrowRight, Users, Lightbulb, Cpu, Globe, Award, Briefcase, DollarSign, ShoppingBag } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export default function AboutUsPage() {
  const ref = useRef<HTMLDivElement>(null)
  const isInView = useInView(ref, { once: true, amount: 0.2 })

  const businessModel = [
    {
      title: "Subscription-Based SaaS",
      description: "PlayMersiv offers a no-code OTT platform on a recurring subscription model, empowering organizations and creators to launch digital experiences instantly.",
      icon: <DollarSign className="h-10 w-10 text-purple-400" />,
    },
    {
      title: "Revenue Share",
      description: "Enables content creators to monetize through subscriptions, sponsorships, ecommerce, NFTs, and more — with a revenue share model for sustainability.",
      icon: <ShoppingBag className="h-10 w-10 text-cyan-400" />,
    },
    {
      title: "Upselling Premium Features",
      description: "Additional revenue is generated by charging for access to advanced AI tools, editing features, Web3 capabilities, and high-quality exports.",
      icon: <Award className="h-10 w-10 text-purple-400" />,
    },
  ]


  const teamMembers = [
    {
      name: "Mohit Lalvani",
      position: "Founder",
      bio: "Also the CEO, he is a former Eleven Sports member and a Harvard Business School student.",
      image: "./mohitsir.png",
    },
    {
      name: "Sandip Talukdar",
      position: "Consulting CFO",
      bio: "He is a Senior Investment Banker and part of the Board Member of Listed Companies",
      image: "/sandipsir.png",
    },
    {
      name: "Malur Narayan",
      position: "Chief Technology Officer",
      bio: "He is a product visionary, Chief Technology Officer, Latimer & Co Founder Cache AI",
      image: "./malursir.png",
    },
    {
      name: "Michael Chua",
      position: "Product Lead",
      bio: "A media specialist, he is also part of fanfare WEB3 Social Commerce and Skyshot, Upside Down",
      image: "./mikesir.png",
    },
  ]

  const milestones = [
    {
      year: "2019",
      title: "1000 Sports Livestream",
      description: "Partnered 40 organisations with 110M minutes of content, generating approx $750,000 revenue",
    },
    {
      year: "2020",
      title: "Enter India Market",
      description: "Launch of Playmersiv SAAS Platform, in partnership with SPORE GOV(Sports SG)",
    },
    {
      year: "2022",
      title: "Launched Podium Web3 Blockchain Platform",
      description: "Partnership with SPORE Ministry of Education",
    },
    {
      year: "2024",
      title: "Oddson Gamification Platform",
      description: "Content Genre Agnostic, Gen AI Integration, Google Partnership, Dulwich Olympiad App and Ayodhya Metaverse",
    },
  ]

  const values = [
    {
      title: "Innovation",
      description: "We constantly push the boundaries of what's possible in media technology.",
      icon: <Lightbulb className="h-10 w-10 text-purple-400" />,
    },
    {
      title: "Excellence",
      description: "We are committed to delivering the highest quality solutions and services.",
      icon: <Award className="h-10 w-10 text-cyan-400" />,
    },
    {
      title: "Collaboration",
      description: "We work closely with our clients to understand and address their unique challenges.",
      icon: <Users className="h-10 w-10 text-purple-400" />,
    },
    {
      title: "Integrity",
      description: "We operate with transparency, honesty, and ethical business practices.",
      icon: <Briefcase className="h-10 w-10 text-cyan-400" />,
    },
    {
      title: "Global Perspective",
      description: "We embrace diversity and think globally in everything we do.",
      icon: <Globe className="h-10 w-10 text-purple-400" />,
    },
    {
      title: "Forward Thinking",
      description: "We anticipate future trends and prepare our clients for what's next.",
      icon: <Cpu className="h-10 w-10 text-cyan-400" />,
    },
  ]

  return (
    <div className="min-h-screen pt-24 pb-16 bg-background text-foreground">
      <div className="container mx-auto px-4">
        <Link
          href="/#about"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-purple-400 transition-colors mb-8"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h1 className="text-3xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400">
            About 1Play Global
          </h1>
          <div className="h-1 w-24 bg-gradient-to-r from-purple-500 to-cyan-500 mx-auto mb-6" />
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            We are pioneers in media technology, dedicated to transforming how content is created, managed, and distributed across the globe.
          </p>
        </motion.div>

        {/* Business Model Section */}
        <div className="mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-3xl font-bold mb-8 text-center"
          >
            Business Model
          </motion.h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {businessModel.map((item, i) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                transition={{ duration: 0.5, delay: 0.1 * i }}
              >
                <Card className="h-full hover:border-primary transition-all duration-300 hover:shadow-lg hover:shadow-purple-500/5">
                  <CardHeader>
                    <div className="mb-4">{item.icon}</div>
                    <CardTitle className="text-xl">{item.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription>{item.description}</CardDescription>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
        <div ref={ref} className="mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ duration: 0.5 }}
            className="text-3xl font-bold mb-8 text-center"
          >
            Our Values
          </motion.h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {values.map((value, i) => (
              <motion.div
                key={value.title}
                initial={{ opacity: 0, y: 20 }}
                animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                transition={{ duration: 0.5, delay: 0.1 * i }}
              >
                <Card className="h-full hover:border-primary transition-all duration-300 hover:shadow-lg hover:shadow-purple-500/5">
                  <CardHeader>
                    <div className="mb-4">{value.icon}</div>
                    <CardTitle className="text-xl">{value.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription>{value.description}</CardDescription>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>

        <div className="mb-16">
          <h2 className="text-3xl font-bold mb-8 text-center">Our Journey</h2>

          <div className="relative">
            <div className="absolute left-1/2 transform -translate-x-1/2 h-full w-1 bg-gradient-to-b from-purple-500 to-cyan-500 rounded-full" />
            <div className="space-y-12">
              {milestones.map((milestone, index) => (
                <div key={milestone.year} className="relative">
                  <div
                    className={`flex items-center ${
                      index % 2 === 0 ? "flex-row" : "flex-row-reverse"
                    } md:flex-row-reverse md:even:flex-row`}
                  >
                    <div className="md:w-1/2 flex justify-center md:justify-end md:even:justify-start">
                      <div className="w-12 h-12 rounded-full bg-gradient-to-r from-purple-500 to-cyan-500 flex items-center justify-center z-10">
                        <span className="font-bold text-white">{milestone.year}</span>
                      </div>
                    </div>
                    <div className="md:w-1/2 pl-6 md:pl-0 md:pr-6 md:even:pl-6 md:even:pr-0">
                      <Card>
                        <CardHeader>
                          <CardTitle>{milestone.title}</CardTitle>
                        </CardHeader>
                        <CardContent>
                          <p>{milestone.description}</p>
                        </CardContent>
                      </Card>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mb-16">
  <h2 className="text-3xl font-bold mb-8 text-center">Leadership Team</h2>

  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    {teamMembers.map((member, index) => (
      <motion.div
        key={member.name}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 * index }}
      >
        <Card className="overflow-hidden">
          <div className="relative h-[400px] w-full">
            <Image
              src={member.image || "/placeholder.svg"}
              alt={member.name}
              fill
              className="object-cover object-center"
            />
          </div>
          <CardHeader>
            <CardTitle>{member.name}</CardTitle>
            <CardDescription>{member.position}</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm">{member.bio}</p>
          </CardContent>
        </Card>
      </motion.div>
    ))}
  </div>
</div>


       

        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">Join Our Team</h2>
          <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
            We're always looking for talented individuals who are passionate about media technology and innovation.
          </p>
          <Link href="/careers">
            <Button
              size="lg"
              className="bg-gradient-to-r from-purple-600 to-cyan-600 hover:from-purple-700 hover:to-cyan-700 text-white"
            >
              View Career Opportunities
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
        </div>
      </div>
    </div>
  )
}